(jsread "emacs.js" "/home/pip/git/ankol")
(js "var console = {log: x => F.message(E(x))};")
(js "ankol(\" say js.F.message(js.E(\\\"hi\\\"))\")")
(js "ankol(\" setq(js.jsfun: jssync({:js.ankol(js.F.buffer-string().toString())}))\")")
(setq jsfun (js "jsfun"))
;;(message "3+1 is %S" (funcall jsfun 3))
(setq ankol-current-buffer nil)
(fset 'ankol-current-buffer jsfun)
(setq f nil)
;;(message "3+1 is also %S" (jsf 3))
(js "AnkolFunction")
(js "AnkolTokenList")
